# Generated by Django 2.2.5 on 2021-08-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressItemTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='user_id')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('gender', models.IntegerField(default=0, verbose_name='is_default')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('complete_address', models.CharField(max_length=100, verbose_name='complete_address')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('latitude', models.CharField(max_length=100, verbose_name='latitude')),
                ('longitude', models.CharField(max_length=100, verbose_name='longitude')),
                ('is_default', models.IntegerField(default=0, verbose_name='is_default')),
            ],
        ),
        migrations.CreateModel(
            name='DiskTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_id', models.IntegerField(default=0, verbose_name='disk_id')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('category_id', models.IntegerField(default=0, verbose_name='category_id')),
                ('is_single', models.BooleanField(default=False, verbose_name='is_single')),
                ('support_takeaway', models.IntegerField(default=0, verbose_name='support_takeaway')),
                ('price', models.CharField(max_length=100, verbose_name='price')),
                ('sort', models.IntegerField(default=0, verbose_name='sort')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_id', models.IntegerField(default=0, verbose_name='disk_id')),
                ('url_0', models.CharField(max_length=100, verbose_name='url_0')),
                ('url_1', models.CharField(max_length=100, verbose_name='url_1')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(default='', max_length=100, verbose_name='openId')),
                ('orderId', models.CharField(max_length=100, verbose_name='orderId')),
                ('sname', models.CharField(max_length=100, verbose_name='sname')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('price', models.CharField(max_length=100, verbose_name='price')),
                ('image', models.CharField(max_length=100, verbose_name='image')),
                ('total_fee', models.IntegerField(default=0, verbose_name='quantity')),
            ],
        ),
        migrations.CreateModel(
            name='MenuTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuId', models.IntegerField(default=0, verbose_name='menuId')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('sort', models.IntegerField(default=0, verbose_name='sort')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.IntegerField(default=0, verbose_name='quantity')),
                ('remarks', models.CharField(max_length=100, verbose_name='remarks')),
                ('payment', models.IntegerField(default=0, verbose_name='quantity')),
                ('shopName', models.CharField(max_length=100, verbose_name='shopName')),
                ('orderId', models.CharField(max_length=100, verbose_name='orderId')),
                ('created_at', models.CharField(max_length=100, verbose_name='created_at')),
                ('userName', models.CharField(max_length=100, verbose_name='userName')),
                ('openId', models.CharField(max_length=100, verbose_name='openId')),
                ('state', models.IntegerField(default=0, verbose_name='state')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100, verbose_name='userId')),
                ('username', models.CharField(max_length=100, verbose_name='userName')),
                ('telphone', models.CharField(max_length=100, verbose_name='telphone')),
                ('gender', models.IntegerField(default=0, verbose_name='is_default')),
                ('birthday', models.CharField(max_length=100, verbose_name='birthday')),
                ('url', models.CharField(max_length=100, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100, verbose_name='userId')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('userName', models.CharField(max_length=100, verbose_name='userName')),
            ],
        ),
    ]
